# Generated by Django 3.1.1 on 2021-02-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210214_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
